- name: Arrancando cluster spark
  hosts: masters
  remote_user: "{{ vm_username }}"
  become: yes
  vars_files:
    - vm-vars.yml

  tasks:

  - name: Arrancando maestro y esclavos Spark
    shell: |
      /opt/app/spark/sbin/start-all.sh
    become: no
    tags:
       - rnspark
